// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetStats():Promise<Record<string, any>>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function SetByteCount(arg1:number):Promise<void>;

export function SetImageCount(arg1:number):Promise<void>;

export function SetTimeCount(arg1:number):Promise<void>;
