// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStats() {
  return window['go']['stat']['Stat']['GetStats']();
}

export function OnStartup(arg1) {
  return window['go']['stat']['Stat']['OnStartup'](arg1);
}

export function SetByteCount(arg1) {
  return window['go']['stat']['Stat']['SetByteCount'](arg1);
}

export function SetImageCount(arg1) {
  return window['go']['stat']['Stat']['SetImageCount'](arg1);
}

export function SetTimeCount(arg1) {
  return window['go']['stat']['Stat']['SetTimeCount'](arg1);
}
