// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppConfig() {
  return window['go']['config']['Config']['GetAppConfig']();
}

export function OnStartup(arg1) {
  return window['go']['config']['Config']['OnStartup'](arg1);
}

export function OpenOutputDir() {
  return window['go']['config']['Config']['OpenOutputDir']();
}

export function RestoreDefaults() {
  return window['go']['config']['Config']['RestoreDefaults']();
}

export function SetConfig(arg1) {
  return window['go']['config']['Config']['SetConfig'](arg1);
}

export function SetOutDir() {
  return window['go']['config']['Config']['SetOutDir']();
}
