// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clear() {
  return window['go']['image']['FileManager']['Clear']();
}

export function Convert() {
  return window['go']['image']['FileManager']['Convert']();
}

export function HandleFile(arg1) {
  return window['go']['image']['FileManager']['HandleFile'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['image']['FileManager']['OnStartup'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['image']['FileManager']['OpenFile'](arg1);
}
